### ISSUE TITLE
Hot reload seems not working using Maui toolkit popup

### ISSUE THREAD

**Issue by jmmortega** [JaneySprings/DotNet.Meteor#131]
There any way to run the hot reload function in diagnostics mode?

I try the tool in a project and seems don't reload in a concrete case. I tried create a minimal project with the things that I'm thinking would be the reason to can't reload, but works. So, if there any way to activate a debug mode where receive the hot reload log or the exception would be really nice to understand what happens and also maybe could share with you.

BTW, kudos for the tool! If you need any hand with something. I'm happy to help.

**Comment by JaneySprings** [comment]
Hi, @jmmortega ! Unfortunately, no. I use MAUI Xaml tools for HotReload and it doesn't have any additional log.

You can try to comment `VisualStateManager` or `x:Name` definitions in your code. It will be nice if you will be able to create any example app for this bug.

**Comment by jmmortega** [comment]
Yes, I tried. I created a minimal reproduction with I'm thinking would be the error, but when test the minimal reproduction, the hot reload works 😅 

So, I not pretty sure why is the main reason that hot reload fails here.

**Comment by jmmortega** [comment]
[HotReloadTest.zip](https://github.com/user-attachments/files/17502269/HotReloadTest.zip)

So, I found the reason that hot reload not working. When using the Community toolkit popups the content inside can't reflect the hot reload changes. 

Share with you a small project to try to reproduce.
- Open the project
- Press the button to navigate to another page.
- Press again the button to go to a popup
- Try to change the popup content to trigger the hot reload


**Expected**: Changes should be reflect.


The weird thing here is... I expect hot reload not working the first time, when you open the popup, but if you create a change and then open the popup again, the changes should be reflected, isn't?

Thank you

Again, if you need anything, ping me.

**Comment by JaneySprings** [comment]
Hi, @jmmortega ! Unfortunately, I can't fix this issue. It seems like a bug (or by design) in the CommunityToolkit popup.

We have two views in the `ChildPage`: ScrollView and Popup. We make changes in the `ChildView : ContentView ` class that is inside of Popup.
But I see that Popup doesn't have any children or logicalChildren in the debugger window:
![image](https://github.com/user-attachments/assets/5a588ba4-68b5-46e1-ac80-ca2dd1774e07)

If this is very important to you, you can ask a question in the [toolkit](https://github.com/CommunityToolkit/Maui/issues) repository
