### ISSUE TITLE
Cant Debug on android local and emulator

### ISSUE THREAD

**Issue by SpiralUniverse** [JaneySprings/DotNet.Meteor#18]
as the title says it builds up and then deploy it and the app opens then the debugger disconnects no error shown where on emulator or physical
[DebugLog.txt](https://github.com/JaneySprings/DotNet.Meteor/files/10252765/DebugLog.txt)

**Comment by JaneySprings** [comment]
Hello. Thank you for your report! In attached log I find this line:

`E/adbd    : failed to connect to socket 'tcp:10000': Connection refused`

In extension settings you can find option `dotnetMeteor.monoSdbDebuggerPortAndroid` with default value 10000. Can you change this value to 11000 or 55551 and tell me if it helped you? It seems to me that in your case something is already using port 10000.

**Comment by SpiralUniverse** [comment]
Okay Long story short is it is working by changing that value 1st at 11000 didn't work then it did on the 2nd one but it is buggy like it might detach on bigger load it did detach the debugger like 3 times in simple maui template anyway I retried on 11000 and it worked I'm not an expert in adb stuff but why does it need port if it is through USB cable? finally, can u add different way of contact like link to discord server or something it's still better than this one for small bugs like this one has turned out not a bug!

**Comment by SpiralUniverse** [comment]
one last thing are u gunna add xaml intellisence? or snippets

**Comment by JaneySprings** [comment]
I use the internet connection since Mono SDB is the server that runs with your application. This is convenient since you have the same approach for Mac iOS and Android.
It's strange to me that you have a busy port 10000. I checked the debugger on different Mac and Windows devices, there were no problems. Even Visual Studio uses this port. If anything you can use any port value, not just 11000.

As for xaml, it's quite a difficult task to generate XSD scheme for assemblies. I was only able to display all available properties:
<img width="612" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/48021947/208288661-09e69758-91d1-4d2e-835e-787e009978bf.png">
I am researching in this direction=)

**Comment by SpiralUniverse** [comment]
> 

hopefully u find a solution! =))

**Comment by SpiralUniverse** [comment]
> Okay Long story short is it is working by changing that value 1st at 11000 didn't work then it did on the 2nd one but it is buggy like it might detach on bigger load it did detach the debugger like 3 times in simple maui template anyway I retried on 11000 and it worked I'm not an expert in adb stuff but why does it need port if it is through USB cable? finally, can u add different way of contact like link to discord server or something it's still better than this one for small bugs like this one has turned out not a bug!

so no discord server for ur extention?

**Comment by JaneySprings** [comment]
I think it will be more comfortable to collect all the reports on GitHub, if you had a problem, someone else will have it too and he will be able to find the answer here.
