### ISSUE TITLE
TargetFramework net7.0-maccatalyst on macOS 13.1 (M1 pro) not working

### ISSUE THREAD

**Issue by kzhui125** [JaneySprings/DotNet.Meteor#35]
if I add  maccatalyst-arm64 RuntimeIdentifier, the app can't start(seems maui problem).

```xml
  <PropertyGroup Condition="'$(TargetFramework)' == 'net7.0-maccatalyst'">
      <RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>
  </PropertyGroup>
```

So how can I debug net7.0-maccatalyst(intel) app?

thanks.

**Comment by JaneySprings** [comment]
Hello! Thank you for your question. If you have Mac with Apple chip you don't need to specify the RuntimeIdentifier property in the csproj file. .NET Meteor automatically adds the desired RuntimeIdentifier depending on the architecture of your Mac. You can see this in the vscode terminal
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/48021947/218243022-4eccf847-47f8-4866-bd3c-a8eaf9b43f02.png">

If you want to build the application for Intel architecture on Mac with Apple chip, you can customize the build task. See [predefined task customization](https://github.com/JaneySprings/DotNet.Meteor/wiki/Predefined-task-customization).

You can create the `tasks.json` file with the following content:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "dotnet-meteor.task",
			"target": "Build",
			"args": [
				"-p:RuntimeIdentifier=maccatalyst-x64"
			],
			"problemMatcher": [],
			"label": "Build MAUI for Mac (Intel)",
		}
	]
}
```
and run it
<img width="608" alt="image" src="https://user-images.githubusercontent.com/48021947/218243361-e923d40c-acb7-4683-b4a5-a6d994f7d923.png">

But in this case, you will not be able to launch the application, since .NET Meteor will search for it in the maccatalyst-arm64 folder. Maybe I should add the ability to run Intel applications for Mac with Apple chip.

**Comment by kzhui125** [comment]
thanks @JaneySprings for your help I can debug now.

But it seems I can only debug cs file, I can't debug razor file. and why is there two startDate in watch...

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/11925432/218252004-ec32e5c7-d174-4fbf-b89c-057a9e39da32.png">

[2023-02-11.gif.zip](https://github.com/JaneySprings/DotNet.Meteor/files/10713112/2023-02-11.gif.zip)

Thanks for your help.

**Comment by JaneySprings** [comment]
I think the Mono Debugger can't resolve breakpoints inside .razor files. I will try to research this issue.

**Comment by JaneySprings** [comment]
Wow. I added '.razor' files to the Mono 'whitelist' and the breakpoints resolved
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/48021947/218278608-411199c1-90fc-493e-9d99-7e89004eb8ee.png">

I will release an update soon and add support for Blazor

**Comment by kzhui125** [comment]
Great!
Thanks a lot.

**Comment by JaneySprings** [comment]
Fixed in https://github.com/JaneySprings/DotNet.Meteor/commit/aad53c5369bc2b34e0939148ebdee7f5f8af62d2
