### ISSUE TITLE
[Feature] Creating new MAUI project from meteor commands

### ISSUE THREAD

**Issue by Pastajello** [JaneySprings/DotNet.Meteor#41]
Hello,

so my idea is, maybe it'd be nice and not as hard to include a 'create new project' command in the meteor command palette.
As MAUI is using templates from CLI I think that this, should? be possible to implement.

Maybe in future.

BTW. love the project!

**Comment by JaneySprings** [comment]
Hello! Thank you for your comment. It is a great idea but I need extra time to research a UI part of this feature (it may require creating a wizard that will configure a new project).

**Comment by scriptBoris** [comment]
I request too 😁

**Comment by JaneySprings** [comment]
As I described above, I do not have resources to implement this functionality. Therefore, I do not plan to add this feature in the nearest future. Still, I keep this inquiry open so that I can return to it when I have enough resources. 

If this functionality is essential in your usage scenario, I recommend that search for alternative extensions as I cannot promise any updates here right now. 

Thank you for your understanding. 

Regards, 
Nikita

**Comment by scottkuhl** [comment]
The new C# Dev Kit seems to make this option no longer needed.
