### ISSUE TITLE
Don't re-install app after  re-debugging

### ISSUE THREAD

**Issue by moonsmile-dev** [JaneySprings/DotNet.Meteor#58]
First, Thank for this project help me develop MAUI app on VSCode <3 
I'm encountering an issue:
- My app has some permissions: external storage/notification. After building and debugging, My App is re-installed and I have to set app permissions again.

**Comment by JaneySprings** [comment]
Hi! Thank you for using Meteor! I had created a fix for your issue but I need some extra time. I will share the fix with our DevExpress Team for testing on Android.

**Comment by moonsmile-dev** [comment]
This issue appears in latest version

**Comment by JaneySprings** [comment]
When I reworked the previous behavior and stopped deleting an older version of the application, I started receiving reports about issues related to the new mechanism. It appears that if an older version of the application already exists on the target device, a new version may not be correctly deployed. 

Unfortunately, I did not find a reliable way to avoid such a side effect. Moreover, this side effects leads to more dramatical issues, because customers may not be able to deploy new applications and they need to manually delete an older version of the application. 

Taking all these points into account, I decided to roll back all these changes. In the current version of the extension I always delete the old version of the application before a new one is deployed. 

I'm afraid, right now I cannot offer to change this behavior. I do apologies.

**Comment by moonsmile-dev** [comment]
`customers may not be able to deploy new applications and they need to manually delete an older version of the application.`
I think this is developer's behavior, when you can't deploy new app, You usually delete `obj`, `bin` folders and delete old apps. I think it's user action instead of your tool, are you?

**Comment by JaneySprings** [comment]
it's very frustrating when you have an old version of your app running. It may take a long time until you notice that your changes in the code are not applied and you need to manually uninstall the application.

**Comment by moonsmile-dev** [comment]
I think we should reopen this issue until there is a solution for it

**Comment by JaneySprings** [comment]
I'll try to add this option in the settings, but I want it to also work on iOS for consistency. I'll check how it will work and make a PR in the near future

**Comment by JaneySprings** [comment]
I added an option for disable app uninstalling in `3.0.3` version
<img width="787" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/a21b925e-4178-44f6-9a29-315d583957bf">

**Comment by SharePointX** [comment]
I just tried the new version and it works as expected.
Thanks very much for your gracious work, it is much appreciated.

**Comment by boer0327** [comment]
@JaneySprings  this tool is fantastic. To be honest it is much better than Visual Studio for Mac.  when you debug on Android device on VS for Mac, it will take an age and sometimes it may fail to deploy. it is totally waste of time.  So I find new world on vs code. Thank you so much. 

but yesterday I met this issue that always redeploys. it will cause my preference and local data to all lost. So every time I need to redo my settings. even a small change. Today, I am reading the issue list. and I found this one. it is really useful for me. Thank you.

I have a suggestion, put this setting description on Read Me. that will help a lot. I almost gave up Meteor before I found this.

**Comment by JaneySprings** [comment]
Hi, @boer0327 ! It's a good idea. In the new version `4.0`, I will make a lot of options for configuring the debugger. I will also write about all the settings in the Readme.

<img width="479" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/bdb118f8-85a0-4287-a71a-4d3bc8793293">

**Comment by boer0327** [comment]
awesome!!! thx, looking forward to your new version.  :)

**Comment by anirudha-teknorix** [comment]
Great work @JaneySprings , I think by default it should be unchecked.
Since on all the other tools like xcode and android studio, it keeps the previous local state of the application.
